title       = "bibleapi"
baseURL     = "https://bibleapi-cli.tamnd.com/"
description = "A command line for bibleapi."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/bibleapi-cli"
